/**
 * Copyright 2007-2008 非也
 * All rights reserved. 
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation。
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see http://www.gnu.org/licenses. *
 */
package org.fireflow.engine.entity.runtime.impl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.nutz.dao.entity.annotation.Table;

// Generated Feb 23, 2008 12:04:21 AM by Hibernate Tools 3.2.0.b9

/**
 * TaskInstance generated by hbm2java
 */
@SuppressWarnings("serial")
@XmlRootElement(name="activityInstance")
@XmlType(name="activityInstanceType")
@XmlAccessorType(XmlAccessType.FIELD)
@Table("T_FF_RT_ACTIVITY_INSTANCE")
public class ActivityInstanceImpl extends AbsActivityInstance implements java.io.Serializable {

 
}
